Chaiyakunapruk_Worawich_final_project/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView

urlpatterns = [

    path('',
         RedirectView.as_view(
             pattern_name='welcome_urlpattern',
             permanent=False
         )),

    path('login/',
         LoginView.as_view(template_name='companyinfo2/login.html'),
         name='login_urlpattern'
         ),

    path('logout/',
         LogoutView.as_view(),
         name='logout_urlpattern'
         ),

    path('about/',
         TemplateView.as_view(
            template_name='companyinfo2/about.html'),
         name='about_urlpattern'
         ),

    path('welcome/',
         TemplateView.as_view(
             template_name='companyinfo2/welcome.html'),
         name='welcome_urlpattern'
         ),

    path('research_product/',
         TemplateView.as_view(
             template_name='companyinfo2/research_product.html'),
         name='research_product_urlpattern'
         ),

    path('news/',
         TemplateView.as_view(
             template_name='companyinfo2/news.html'),
         name='news_urlpattern'
         ),

    path('store/',
         TemplateView.as_view(
             template_name='companyinfo2/store.html'),
         name='store_urlpattern'
         ),

    path('admin/', admin.site.urls),

    path('', include('companyinfo2.urls'))

]

companyinfo2/urls.py
from django.urls import path

from .views import (
    AssemblingList,
    ProductList,
    PartList,
    SupplierList,
    CoordinatorList,
    Product_coordinatorList,
    AssemblingDetail,
    ProductDetail,
    PartDetail,
    SupplierDetail,
    CoordinatorDetail,
    Product_coordinatorDetail,
    AssemblingCreate,
    AssemblingUpdate,
    AssemblingDelete,
    ProductCreate,
    ProductUpdate,
    ProductDelete,
    PartCreate,
    PartUpdate,
    PartDelete,
    SupplierCreate,
    SupplierUpdate,
    SupplierDelete,
    CoordinatorCreate,
    CoordinatorUpdate,
    CoordinatorDelete,
    Product_coordinatorCreate,
    Product_coordinatorUpdate,
    Product_coordinatorDelete,
    # AddressCreate,
    # AddressUpdate,
    # AddressDelete,
    # BillingCreate,
    # BillingUpdate,
    # BillingDelete,
)

urlpatterns = [

    path('assembling/',
         AssemblingList.as_view(),
         name='companyinfo2_assembling_list_urlpattern'),

    path('assembling/<int:pk>/',
        AssemblingDetail.as_view(),
        name='companyinfo2_assembling_detail_urlpattern'),

    path('assembling/create/',
         AssemblingCreate.as_view(),
         name='companyinfo2_assembling_create_urlpattern'),

    path('assembling/<int:pk>/update/',
         AssemblingUpdate.as_view(),
         name='companyinfo2_assembling_update_urlpattern'),

    path('assembling/<int:pk>/delete/',
         AssemblingDelete.as_view(),
         name='companyinfo2_assembling_delete_urlpattern'),

    path('product/',
         ProductList.as_view(),
         name='companyinfo2_product_list_urlpattern'),

    path('product/<int:pk>/',
        ProductDetail.as_view(),
        name='companyinfo2_product_detail_urlpattern'),

    path('product/create/',
         ProductCreate.as_view(),
         name='companyinfo2_product_create_urlpattern'),

    path('product/<int:pk>/update/',
         ProductUpdate.as_view(),
         name='companyinfo2_product_update_urlpattern'),

    path('product/<int:pk>/delete/',
         ProductDelete.as_view(),
         name='companyinfo2_product_delete_urlpattern'),

    path('part/',
         PartList.as_view(),
         name='companyinfo2_part_list_urlpattern'),

    path('part/<int:pk>/',
        PartDetail.as_view(),
        name='companyinfo2_part_detail_urlpattern'),

    path('part/create/',
         PartCreate.as_view(),
         name='companyinfo2_part_create_urlpattern'),

    path('part/<int:pk>/update/',
         PartUpdate.as_view(),
         name='companyinfo2_part_update_urlpattern'),

    path('part/<int:pk>/delete/',
         PartDelete.as_view(),
         name='companyinfo2_part_delete_urlpattern'),

    path('supplier/<int:pk>/',
        SupplierDetail.as_view(),
        name='companyinfo2_supplier_detail_urlpattern'),

    path('supplier/',
         SupplierList.as_view(),
         name='companyinfo2_supplier_list_urlpattern'),

    path('supplier/create/',
         SupplierCreate.as_view(),
         name='companyinfo2_supplier_create_urlpattern'),

    path('supplier/<int:pk>/update/',
         SupplierUpdate.as_view(),
         name='companyinfo2_supplier_update_urlpattern'),

    path('supplier/<int:pk>/delete/',
         SupplierDelete.as_view(),
         name='companyinfo2_supplier_delete_urlpattern'),

    path('coordinator/',
         CoordinatorList.as_view(),
         name='companyinfo2_coordinator_list_urlpattern'),

    path('coordinator/<int:pk>/',
        CoordinatorDetail.as_view(),
        name='companyinfo2_coordinator_detail_urlpattern'),

    path('coordinator/create/',
         CoordinatorCreate.as_view(),
         name='companyinfo2_coordinator_create_urlpattern'),

    path('coordinator/<int:pk>/update/',
         CoordinatorUpdate.as_view(),
         name='companyinfo2_coordinator_update_urlpattern'),

    path('coordinator/<int:pk>/delete/',
         CoordinatorDelete.as_view(),
         name='companyinfo2_coordinator_delete_urlpattern'),

    path('product_coordinator/',
         Product_coordinatorList.as_view(),
         name='companyinfo2_product_coordinator_list_urlpattern'),

    path('product_coordinator/<int:pk>/',
         Product_coordinatorDetail.as_view(),
         name='companyinfo2_product_coordinator_detail_urlpattern'),

    path('product_coordinator/create/',
         Product_coordinatorCreate.as_view(),
         name='companyinfo2_product_coordinator_create_urlpattern'),

    path('product_coordinator/<int:pk>/update/',
         Product_coordinatorUpdate.as_view(),
         name='companyinfo2_product_coordinator_update_urlpattern'),

    path('product_coordinator/<int:pk>/delete/',
         Product_coordinatorDelete.as_view(),
         name='companyinfo2_product_coordinator_delete_urlpattern'),

]

companyinfo2/models.py
from django.db import models
from django.urls import reverse


class Assembling(models.Model):
    assembling_id = models.AutoField(primary_key=True)
    assembling_code = models.CharField(max_length=45)
    assembling_line = models.CharField(max_length=45)

    def __str__(self):
        return '%s, %s' % (self.assembling_code, self.assembling_line)

    def get_absolute_url(self):
        return reverse('companyinfo2_assembling_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('companyinfo2_assembling_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse(
            'companyinfo2_assembling_delete_urlpattern',
            kwargs={'pk': self.pk}
        )

    class Meta:
        ordering = ['assembling_code', 'assembling_line']
        unique_together = (('assembling_code', 'assembling_line'),)


class State(models.Model):
    state_id = models.AutoField(primary_key=True)
    state_name = models.CharField(max_length=45, unique=True)
    state_code = models.CharField(max_length=5, unique=True)

    def __str__(self):
        return '%s - %s' % (self.state_code, self.state_name)

    class Meta:
        ordering = ['state_code', 'state_name']


class Country(models.Model):
    country_id = models.AutoField(primary_key=True)
    country_name = models.CharField(max_length=45, unique=True)
    country_code = models.CharField(max_length=5, unique=True)

    def __str__(self):
        return '%s - %s' % (self.country_code, self.country_name)

    class Meta:
        ordering = ['country_code', 'country_name']
        
        
class Address(models.Model):
    address_id = models.AutoField(primary_key=True)
    address_name = models.CharField(max_length=45, unique=True)
    address_number = models.IntegerField(unique=False)
    street_name = models.CharField(max_length=45, unique=False)
    district_name = models.CharField(max_length=45, unique=False)
    city_name = models.CharField(max_length=45, unique=False)
    state = models.ForeignKey(State, related_name='addresses', on_delete=models.PROTECT)
    country = models.ForeignKey(Country, related_name='addresses', on_delete=models.PROTECT)

    def __str__(self):
        return '%s - %s' % (self.address_name, self.city_name, self.state, self.country)

    def get_absolute_url(self):
        return reverse('companyinfo2_address_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('companyinfo2_address_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('companyinfo2_address_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['country', 'state', 'city_name', 'address_name']
        

class Tier(models.Model):
    tier_id = models.AutoField(primary_key=True)
    tier_level = models.IntegerField(unique=True)
    tier_name = models.CharField(max_length=45,unique=True)

    def __str__(self):
        return '%s - %s' % (self.tier_level, self.tier_name)

    class Meta:
        ordering = ['tier_level']


# Attempt to create tier failed.

# class Supplier(models.Model):
#     supplier_id = models.AutoField(primary_key=True)
#     supplier_name = models.CharField(max_length=45, unique=True)
#     tier = models.ForeignKey(Tier, related_name='suppliers', on_delete=models.PROTECT)
#     address = models.ForeignKey(Address, related_name='suppliers', on_delete=models.PROTECT)
#
#     def __str__(self):
#         return '%s - %s' % (self.tier, self.supplier_name, self.address)
#
#     def get_absolute_url(self):
#         return reverse('companyinfo2_supplier_detail_urlpattern',
#                        kwargs={'pk': self.pk})
#
#     def get_update_url(self):
#         return reverse('companyinfo2_supplier_update_urlpattern',
#                        kwargs={'pk': self.pk}
#                        )
#
#     def get_delete_url(self):
#         return reverse('companyinfo2_supplier_delete_urlpattern',
#                        kwargs={'pk': self.pk}
#                        )
#
#     class Meta:
#         ordering = ['tier__tier_level', 'supplier_name', 'address']


class Supplier(models.Model):
    supplier_id = models.AutoField(primary_key=True)
    supplier_name = models.CharField(max_length=45, unique=True)

    def __str__(self):
        return '%s' % self.supplier_name

    def get_absolute_url(self):
        return reverse('companyinfo2_supplier_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('companyinfo2_supplier_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('companyinfo2_supplier_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['supplier_name']


class Part(models.Model):
    part_id = models.AutoField(primary_key=True)
    part_number = models.CharField(max_length=20)
    part_name = models.CharField(max_length=255)

    def __str__(self):
        return '%s - %s' % (self.part_number, self.part_name)

    def get_absolute_url(self):
        return reverse('companyinfo2_part_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('companyinfo2_part_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('companyinfo2_part_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['part_number', 'part_name']
        unique_together = (('part_number', 'part_name'),)


class Coordinator(models.Model):
    coordinator_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    nickname = models.CharField(max_length=45, blank=True, default='')

    def __str__(self):
        result = ''
        if self.nickname == '':
            result = '%s, %s' % (self.last_name, self.first_name)
        else:
            result = '%s, %s (%s)' % (self.last_name, self.first_name, self.nickname)
        return result

    def get_absolute_url(self):
        return reverse('companyinfo2_coordinator_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('companyinfo2_coordinator_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('companyinfo2_coordinator_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['last_name', 'first_name', 'nickname']
        unique_together = (('last_name', 'first_name', 'nickname'),)


class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=45)
    supplier = models.ForeignKey(Supplier, related_name='products', on_delete=models.PROTECT)
    part = models.ForeignKey(Part, related_name='products', on_delete=models.PROTECT)
    assembling = models.ForeignKey(Assembling, related_name='products', on_delete=models.PROTECT)

    def __str__(self):
        return '%s - %s (%s)' % (self.part.part_number, self.product_name, self.supplier.__str__())

    def get_absolute_url(self):
        return reverse('companyinfo2_product_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('companyinfo2_product_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('companyinfo2_product_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['part__part_number', 'product_name', 'supplier__supplier_name']
        unique_together = (('supplier', 'part', 'product_name'),)


class Product_coordinator(models.Model):
    product_coordinator_id = models.AutoField(primary_key=True)
    coordinator = models.ForeignKey(Coordinator, related_name='product_coordinators',  on_delete=models.PROTECT)
    product = models.ForeignKey(Product, related_name='product_coordinators',  on_delete=models.PROTECT)

    def __str__(self):
        return '%s / %s' % (self.product, self.coordinator)

    def get_absolute_url(self):
        return reverse('companyinfo2_product_coordinator_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('companyinfo2_product_coordinator_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('companyinfo2_product_coordinator_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['product', 'coordinator']
        unique_together = (('product', 'coordinator'),)


class Billing(models.Model):
    billing_id = models.AutoField(primary_key=True)
    billing_number = models.IntegerField(unique=True)
    billing_name = models.CharField(max_length=45, unique=True)
    supplier = models.ForeignKey(Supplier, related_name='billings', on_delete=models.PROTECT)
    address = models.ForeignKey(Address, related_name='billings', on_delete=models.PROTECT)

    def __str__(self):
        return '%s %s - %s' % (self.supplier.supplier_id, self.supplier.supplier_name, self.billing_number)

companyinfo2/templates/companyinfo2/coordinator_form_update.html
{% extends 'companyinfo2/base.html' %}

{% block title %}
    Update Coordinator
{% endblock %}

{% block content %}
    <form
        action="{{ coordinator.get_update_url }}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Coordinator</button>
    </form>
{% endblock %}

companyinfo2/templates/companyinfo2/coordinator_list.html
{% extends 'companyinfo2/base.html' %}

{% block title %}
    Coordinator List
{% endblock %}

{% block org_content %}
  <h2>Coordinator List</h2>
    {% if perms.companyinfo2.add_coordinator %}
    <div class="mobile">
      <a
          href="{% url 'companyinfo2_coordinator_create_urlpattern' %}"
          class="button button-primary">
        Create New Coordinator</a>
    </div>
    {% endif %}
  <ul>
    {% for coordinator in coordinator_list %}
      <li>
        <a href="{{ coordinator.get_absolute_url }}">
          {{ coordinator }}</a>
      </li>
    {% empty %}
      <li><em>There are currently no coordinators available.</em></li>
    {% endfor %}
  </ul>
{% endblock %}

companyinfo2/templates/companyinfo2/coordinator_refuse_delete.html
{% extends 'companyinfo2/base.html' %}

{% block title %}
    Error Deleting Coordinator
{% endblock %}

{% block content %}
    <div>
        <h2>Error Deleting Coordinator</h2>
        <p>
            You may not delete coordinator {{ coordinator }}.  This
            coordinator is currently registered in the following
            products:
        </p>

        <ul>
            {% for product_coordinator in product_coordinators %}
            <li><a href="{{ product_coordinator.get_absolute_url }}">{{ product_coordinator.product }}</a></li>
            {%  endfor %}
        </ul>

        <p>
            Return to <a href="{% url 'companyinfo2_coordinator_list_urlpattern' %}">Coordinator List</a>.
        </p>
    </div>
{% endblock %}

companyinfo2/templates/companyinfo2/logged_in.html
{% extends 'companyinfo2/base.html' %}

{% block title %}
    You are in the employee module
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
    <h2>You are in the employee module</h2>
    <p>You are now in the employee module, which includes the company system functions. To view customer functions,
        please log out.</p>
    </div>
  </div>
{% endblock %}

companyinfo2/templates/companyinfo2/news.html
{% extends 'companyinfo2/base.html' %}

{% block title %}
    News
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
    <h2>News</h2>
    <p>This page will have news about the company and the industry.</p>
    </div>
  </div>
{% endblock %}

companyinfo2/templates/companyinfo2/part_detail.html
{% extends 'companyinfo2/base.html' %}

{% block title %}
    Part - {{ part }}
{% endblock %}

{% block content %}
<article>
  <div class="row">
  <div class="offset-by-two eight columns">
    <h2>{{ part }}</h2>
    <ul class="inline">
        {% if perms.companyinfo2.change_part %}
        <li>
          <a
              href="{{ part.get_update_url }}"
              class="button">
            Edit Part</a></li>
        {% endif %}
        {% if perms.companyinfo2.delete_part %}
        <li>
          <a
              href="{{ part.get_delete_url }}"
              class="button">
            Delete Part</a></li>
        {% endif %}
    </ul>
    <section>
        <table>
            <tr>
                <th>Part Number:</th>
                <td>{{ part.part_number }}</td>
            </tr>
            <tr>
                <th>Part Name:</th>
                <td>{{ part.part_name }}</td>
            </tr>
        </table>
    </section>

    <section>
        <h3>Products</h3>
        <ul>
            {% for product in product_list %}
                <li>
                    <a href="{{ product.get_absolute_url }}">{{ product }}</a>
                </li>
            {% empty %}
                <li><em>There are currently no products for this part.</em></li>
            {% endfor %}
        </ul>
    </section>
  </div></div> <!-- row -->

</article>
{% endblock %}

companyinfo2/templates/companyinfo2/product_confirm_delete.html
{% extends 'companyinfo2/base.html' %}

{% block title %}
    Delete Product
{% endblock %}

{% block content %}
    <form
        action="{{ product.get_delete_url }}"
        method="post">
        {% csrf_token %}
        <p>
            Are you sure that you want to delete
            product {{ product }}?
        </p>
        <a href="{{ product.get_absolute_url }}">Cancel</a>
        <button type="submit">Delete Product</button>
    </form>
{% endblock %}

companyinfo2/templates/companyinfo2/product_coordinator_confirm_delete.html
{% extends 'companyinfo2/base.html' %}

{% block title %}
    Delete Product_coordinator
{% endblock %}

{% block content %}
    <form
        action="{{ product_coordinator.get_delete_url }}"
        method="post">
        {% csrf_token %}
        <p>
            Are you sure that you want to delete
            product_coordinator {{ product_coordinator }}?
        </p>
        <a href="{{ product_coordinator.get_absolute_url }}">Cancel</a>
        <button type="submit">Delete Product_coordinator</button>
    </form>
{% endblock %}

companyinfo2/templates/companyinfo2/product_coordinator_detail.html
{% extends 'companyinfo2/base.html' %}

{% block title %}
    Product_coordinator - {{ product_coordinator }}
{% endblock %}

{% block content %}
<article>
  <div class="row">
  <div class="offset-by-two eight columns">
    <h2>{{ coordinator }}</h2>
    <ul class="inline">
        {% if perms.companyinfo2.change_coordinator %}
        <li>
          <a href="{{ product_coordinator.get_update_url }}"
          class="button">
            Edit Product_coordinator</a></li>
        {% endif %}
        {% if perms.companyinfo2.delete_coordinator %}
        <li>
          <a href="{{ product_coordinator.get_delete_url }}"
          class="button">
            Delete Product_coordinator</a></li>
        {% endif %}
    </ul>
    <section>
        <table>
            <tr>
                <th>Coordinator:</th>
                <td><a href="{{ coordinator.get_absolute_url }}">{{ coordinator }}</a></td>
            </tr>
            <tr>
                <th>Product:</th>
                <td><a href="{{ product.get_absolute_url }}">{{ product }}</a></td>
            </tr>
        </table>
    </section>

  </div></div> <!-- row -->

</article>
{% endblock %}

companyinfo2/templates/companyinfo2/product_coordinator_form_update.html
{% extends 'companyinfo2/base.html' %}

{% block title %}
    Update Product_coordinator
{% endblock %}

{% block content %}
    <form
        action="{{ product_coordinator.get_update_url }}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Product_coordinator</button>
    </form>
{% endblock %}

companyinfo2/templates/companyinfo2/product_detail.html
{% extends 'companyinfo2/base.html' %}

{% block title %}
    Product - {{ product }}
{% endblock %}

{% block content %}
    <article>
        <div class="row">
            <div class="offset-by-two eight columns">
                <h2>{{ product }}</h2>
                <ul class="inline">
                    {% if perms.companyinfo2.change_product %}
                    <li>
                        <a href="{{ product.get_update_url }}"
                           class="button">
                            Edit Product</a></li>
                    {% endif %}
                    {% if perms.companyinfo2.delete_product %}
                    <li>
                        <a href="{{ product.get_delete_url }}"
                           class="button">
                            Delete Product</a></li>
                    {% endif %}
                </ul>

                   <section>
        <table>
            <tr>
                <th>Part:</th>
                <td><a href="{{ part.get_absolute_url }}">{{ part }}</a></td>
            </tr>
            <tr>
                <th>Product Name:</th>
                <td>{{ product.product_name }}</td>
            </tr>
            <tr>
                <th>Supplier:</th>
                <td><a href="{{ supplier.get_absolute_url }}">{{ supplier }}</a></td>
            </tr>

            <tr>
                <th>Assembling:</th>
                <td><a href="{{ assembling.get_absolute_url }}">{{ assembling }}</a></td>
            </tr>
        </table>

    </section>

    <section>
        <h3>Product Coordinators</h3>
        <ul>
            {% for product_coordinator in product_coordinator_list %}
                <li>
                    <a href="{{ product_coordinator.get_absolute_url }}">{{ product_coordinator.coordinator }}</a>
                </li>
            {% empty %}
                <li><em>There are currently no coordinators registered for this product.</em></li>
            {% endfor %}
        </ul>
    </section>

            </div>
        </div> <!-- row -->

    </article>
{% endblock %}

companyinfo2/templates/companyinfo2/product_form_update.html
{% extends 'companyinfo2/base.html' %}

{% block title %}
    Update Product
{% endblock %}

{% block content %}
    <form
        action="{{ product.get_update_url }}"
        method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Product</button>
    </form>
{% endblock %}

companyinfo2/templates/companyinfo2/store.html
{% extends 'companyinfo2/base.html' %}

{% block title %}
    Store
{% endblock %}

{% block content %}
  <div class="row">
    <div class="offset-by-two eight columns">
    <h2>Store</h2>
    <p>This is the store page, where I will put the whole system of E-commerce that will also be build on Django.
    It will include another set of authentication.</p>
    </div>
  </div>
{% endblock %}

companyinfo2/templates/companyinfo2/supplier_refuse_delete.html
{% extends 'companyinfo2/base.html' %}

{% block title %}
    Error Deleting Supplier
{% endblock %}

{% block content %}
    <div>
        <h2>Error Deleting Supplier</h2>
        <p>
            You may not delete supplier {{ supplier }}.  This
            supplier is currently associated with the following
            products:
        </p>

        <ul>
            {% for product in products %}
            <li><a href="{{ product.get_absolute_url }}">{{ product }}</a></li>
            {%  endfor %}
        </ul>

        <p>
            Return to <a href="{% url 'companyinfo2_supplier_list_urlpattern' %}">Supplier List</a>.
        </p>
    </div>
{% endblock %}