Chaiyakunapruk_Worawich_final_project/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.views.generic import RedirectView, TemplateView

urlpatterns = [

    path('',
         RedirectView.as_view(
             pattern_name='welcome_urlpattern',
             permanent=False
         )),

    path('login/',
         LoginView.as_view(template_name='companyinfo2/login.html'),
         name='login_urlpattern'
         ),

    path('logout/',
         LogoutView.as_view(),
         name='logout_urlpattern'
         ),

    path('about/',
         TemplateView.as_view(
            template_name='companyinfo2/about.html'),
         name='about_urlpattern'
         ),

    path('welcome/',
         TemplateView.as_view(
             template_name='companyinfo2/welcome.html'),
         name='welcome_urlpattern'
         ),

    path('research_product/',
         TemplateView.as_view(
             template_name='companyinfo2/research_product.html'),
         name='research_product_urlpattern'
         ),

    path('news/',
         TemplateView.as_view(
             template_name='companyinfo2/news.html'),
         name='news_urlpattern'
         ),

    path('store/',
         TemplateView.as_view(
             template_name='companyinfo2/store.html'),
         name='store_urlpattern'
         ),

    path('admin/', admin.site.urls),

    path('', include('companyinfo2.urls'))

]

companyinfo2/urls.py
from django.urls import path

from .views import (
    AssemblingList,
    ProductList,
    PartList,
    SupplierList,
    CoordinatorList,
    Product_coordinatorList,
    AssemblingDetail,
    ProductDetail,
    PartDetail,
    SupplierDetail,
    CoordinatorDetail,
    Product_coordinatorDetail,
    AssemblingCreate,
    AssemblingUpdate,
    AssemblingDelete,
    ProductCreate,
    ProductUpdate,
    ProductDelete,
    PartCreate,
    PartUpdate,
    PartDelete,
    SupplierCreate,
    SupplierUpdate,
    SupplierDelete,
    CoordinatorCreate,
    CoordinatorUpdate,
    CoordinatorDelete,
    Product_coordinatorCreate,
    Product_coordinatorUpdate,
    Product_coordinatorDelete,
    # AddressCreate,
    # AddressUpdate,
    # AddressDelete,
    # BillingCreate,
    # BillingUpdate,
    # BillingDelete,
)

urlpatterns = [

    path('assembling/',
         AssemblingList.as_view(),
         name='companyinfo2_assembling_list_urlpattern'),

    path('assembling/<int:pk>/',
        AssemblingDetail.as_view(),
        name='companyinfo2_assembling_detail_urlpattern'),

    path('assembling/create/',
         AssemblingCreate.as_view(),
         name='companyinfo2_assembling_create_urlpattern'),

    path('assembling/<int:pk>/update/',
         AssemblingUpdate.as_view(),
         name='companyinfo2_assembling_update_urlpattern'),

    path('assembling/<int:pk>/delete/',
         AssemblingDelete.as_view(),
         name='companyinfo2_assembling_delete_urlpattern'),

    path('product/',
         ProductList.as_view(),
         name='companyinfo2_product_list_urlpattern'),

    path('product/<int:pk>/',
        ProductDetail.as_view(),
        name='companyinfo2_product_detail_urlpattern'),

    path('product/create/',
         ProductCreate.as_view(),
         name='companyinfo2_product_create_urlpattern'),

    path('product/<int:pk>/update/',
         ProductUpdate.as_view(),
         name='companyinfo2_product_update_urlpattern'),

    path('product/<int:pk>/delete/',
         ProductDelete.as_view(),
         name='companyinfo2_product_delete_urlpattern'),

    path('part/',
         PartList.as_view(),
         name='companyinfo2_part_list_urlpattern'),

    path('part/<int:pk>/',
        PartDetail.as_view(),
        name='companyinfo2_part_detail_urlpattern'),

    path('part/create/',
         PartCreate.as_view(),
         name='companyinfo2_part_create_urlpattern'),

    path('part/<int:pk>/update/',
         PartUpdate.as_view(),
         name='companyinfo2_part_update_urlpattern'),

    path('part/<int:pk>/delete/',
         PartDelete.as_view(),
         name='companyinfo2_part_delete_urlpattern'),

    path('supplier/<int:pk>/',
        SupplierDetail.as_view(),
        name='companyinfo2_supplier_detail_urlpattern'),

    path('supplier/',
         SupplierList.as_view(),
         name='companyinfo2_supplier_list_urlpattern'),

    path('supplier/create/',
         SupplierCreate.as_view(),
         name='companyinfo2_supplier_create_urlpattern'),

    path('supplier/<int:pk>/update/',
         SupplierUpdate.as_view(),
         name='companyinfo2_supplier_update_urlpattern'),

    path('supplier/<int:pk>/delete/',
         SupplierDelete.as_view(),
         name='companyinfo2_supplier_delete_urlpattern'),

    path('coordinator/',
         CoordinatorList.as_view(),
         name='companyinfo2_coordinator_list_urlpattern'),

    path('coordinator/<int:pk>/',
        CoordinatorDetail.as_view(),
        name='companyinfo2_coordinator_detail_urlpattern'),

    path('coordinator/create/',
         CoordinatorCreate.as_view(),
         name='companyinfo2_coordinator_create_urlpattern'),

    path('coordinator/<int:pk>/update/',
         CoordinatorUpdate.as_view(),
         name='companyinfo2_coordinator_update_urlpattern'),

    path('coordinator/<int:pk>/delete/',
         CoordinatorDelete.as_view(),
         name='companyinfo2_coordinator_delete_urlpattern'),

    path('product_coordinator/',
         Product_coordinatorList.as_view(),
         name='companyinfo2_product_coordinator_list_urlpattern'),

    path('product_coordinator/<int:pk>/',
         Product_coordinatorDetail.as_view(),
         name='companyinfo2_product_coordinator_detail_urlpattern'),

    path('product_coordinator/create/',
         Product_coordinatorCreate.as_view(),
         name='companyinfo2_product_coordinator_create_urlpattern'),

    path('product_coordinator/<int:pk>/update/',
         Product_coordinatorUpdate.as_view(),
         name='companyinfo2_product_coordinator_update_urlpattern'),

    path('product_coordinator/<int:pk>/delete/',
         Product_coordinatorDelete.as_view(),
         name='companyinfo2_product_coordinator_delete_urlpattern'),

]

companyinfo2/models.py
from django.db import models
from django.urls import reverse


class Assembling(models.Model):
    assembling_id = models.AutoField(primary_key=True)
    assembling_code = models.CharField(max_length=45)
    assembling_line = models.CharField(max_length=45)

    def __str__(self):
        return '%s, %s' % (self.assembling_code, self.assembling_line)

    def get_absolute_url(self):
        return reverse('companyinfo2_assembling_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('companyinfo2_assembling_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse(
            'companyinfo2_assembling_delete_urlpattern',
            kwargs={'pk': self.pk}
        )

    class Meta:
        ordering = ['assembling_code', 'assembling_line']
        unique_together = (('assembling_code', 'assembling_line'),)


class State(models.Model):
    state_id = models.AutoField(primary_key=True)
    state_name = models.CharField(max_length=45, unique=True)
    state_code = models.CharField(max_length=5, unique=True)

    def __str__(self):
        return '%s - %s' % (self.state_code, self.state_name)

    class Meta:
        ordering = ['state_code', 'state_name']


class Country(models.Model):
    country_id = models.AutoField(primary_key=True)
    country_name = models.CharField(max_length=45, unique=True)
    country_code = models.CharField(max_length=5, unique=True)

    def __str__(self):
        return '%s - %s' % (self.country_code, self.country_name)

    class Meta:
        ordering = ['country_code', 'country_name']
        
        
class Address(models.Model):
    address_id = models.AutoField(primary_key=True)
    address_name = models.CharField(max_length=45, unique=True)
    address_number = models.IntegerField(unique=False)
    street_name = models.CharField(max_length=45, unique=False)
    district_name = models.CharField(max_length=45, unique=False)
    city_name = models.CharField(max_length=45, unique=False)
    state = models.ForeignKey(State, related_name='addresses', on_delete=models.PROTECT)
    country = models.ForeignKey(Country, related_name='addresses', on_delete=models.PROTECT)

    def __str__(self):
        return '%s - %s' % (self.address_name, self.city_name, self.state, self.country)

    def get_absolute_url(self):
        return reverse('companyinfo2_address_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('companyinfo2_address_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('companyinfo2_address_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['country', 'state', 'city_name', 'address_name']
        

class Tier(models.Model):
    tier_id = models.AutoField(primary_key=True)
    tier_level = models.IntegerField(unique=True)
    tier_name = models.CharField(max_length=45,unique=True)

    def __str__(self):
        return '%s - %s' % (self.tier_level, self.tier_name)

    class Meta:
        ordering = ['tier_level']


# Attempt to create tier failed.

# class Supplier(models.Model):
#     supplier_id = models.AutoField(primary_key=True)
#     supplier_name = models.CharField(max_length=45, unique=True)
#     tier = models.ForeignKey(Tier, related_name='suppliers', on_delete=models.PROTECT)
#     address = models.ForeignKey(Address, related_name='suppliers', on_delete=models.PROTECT)
#
#     def __str__(self):
#         return '%s - %s' % (self.tier, self.supplier_name, self.address)
#
#     def get_absolute_url(self):
#         return reverse('companyinfo2_supplier_detail_urlpattern',
#                        kwargs={'pk': self.pk})
#
#     def get_update_url(self):
#         return reverse('companyinfo2_supplier_update_urlpattern',
#                        kwargs={'pk': self.pk}
#                        )
#
#     def get_delete_url(self):
#         return reverse('companyinfo2_supplier_delete_urlpattern',
#                        kwargs={'pk': self.pk}
#                        )
#
#     class Meta:
#         ordering = ['tier__tier_level', 'supplier_name', 'address']


class Supplier(models.Model):
    supplier_id = models.AutoField(primary_key=True)
    supplier_name = models.CharField(max_length=45, unique=True)

    def __str__(self):
        return '%s' % self.supplier_name

    def get_absolute_url(self):
        return reverse('companyinfo2_supplier_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('companyinfo2_supplier_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('companyinfo2_supplier_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['supplier_name']


class Part(models.Model):
    part_id = models.AutoField(primary_key=True)
    part_number = models.CharField(max_length=20)
    part_name = models.CharField(max_length=255)

    def __str__(self):
        return '%s - %s' % (self.part_number, self.part_name)

    def get_absolute_url(self):
        return reverse('companyinfo2_part_detail_urlpattern',
                       kwargs={'pk': self.pk})

    def get_update_url(self):
        return reverse('companyinfo2_part_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('companyinfo2_part_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['part_number', 'part_name']
        unique_together = (('part_number', 'part_name'),)


class Coordinator(models.Model):
    coordinator_id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    nickname = models.CharField(max_length=45, blank=True, default='')

    def __str__(self):
        result = ''
        if self.nickname == '':
            result = '%s, %s' % (self.last_name, self.first_name)
        else:
            result = '%s, %s (%s)' % (self.last_name, self.first_name, self.nickname)
        return result

    def get_absolute_url(self):
        return reverse('companyinfo2_coordinator_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('companyinfo2_coordinator_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('companyinfo2_coordinator_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['last_name', 'first_name', 'nickname']
        unique_together = (('last_name', 'first_name', 'nickname'),)


class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=45)
    supplier = models.ForeignKey(Supplier, related_name='products', on_delete=models.PROTECT)
    part = models.ForeignKey(Part, related_name='products', on_delete=models.PROTECT)
    assembling = models.ForeignKey(Assembling, related_name='products', on_delete=models.PROTECT)

    def __str__(self):
        return '%s - %s (%s)' % (self.part.part_number, self.product_name, self.supplier.__str__())

    def get_absolute_url(self):
        return reverse('companyinfo2_product_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('companyinfo2_product_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('companyinfo2_product_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['part__part_number', 'product_name', 'supplier__supplier_name']
        unique_together = (('supplier', 'part', 'product_name'),)


class Product_coordinator(models.Model):
    product_coordinator_id = models.AutoField(primary_key=True)
    coordinator = models.ForeignKey(Coordinator, related_name='product_coordinators',  on_delete=models.PROTECT)
    product = models.ForeignKey(Product, related_name='product_coordinators',  on_delete=models.PROTECT)

    def __str__(self):
        return '%s / %s' % (self.product, self.coordinator)

    def get_absolute_url(self):
        return reverse('companyinfo2_product_coordinator_detail_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_update_url(self):
        return reverse('companyinfo2_product_coordinator_update_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    def get_delete_url(self):
        return reverse('companyinfo2_product_coordinator_delete_urlpattern',
                       kwargs={'pk': self.pk}
                       )

    class Meta:
        ordering = ['product', 'coordinator']
        unique_together = (('product', 'coordinator'),)


class Billing(models.Model):
    billing_id = models.AutoField(primary_key=True)
    billing_number = models.IntegerField(unique=True)
    billing_name = models.CharField(max_length=45, unique=True)
    supplier = models.ForeignKey(Supplier, related_name='billings', on_delete=models.PROTECT)
    address = models.ForeignKey(Address, related_name='billings', on_delete=models.PROTECT)

    def __str__(self):
        return '%s %s - %s' % (self.supplier.supplier_id, self.supplier.supplier_name, self.billing_number)

templates/companyinfo/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            title is provided by inheriting templates
        {% endblock %}
    </title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--[if IE]><script
      src="http://html5shiv.googlecode.com/svn/trunk/html5.js">
    </script><![endif]-->
</head>

<body>

<div><!-- start of container -->
    <header>
        <h1>EZ Company</h1>
        <h2>Innovation research and retailer</h2>
    </header>
    <nav>
        <ul>
{#            {% if perms.companyinfo2.view_assembling %}#}
                <li>
                    <a href="{% url 'companyinfo_assembling_list_urlpattern' %}">
                        Assemblings</a></li>
{#            {% endif %}#}

{#            {% if perms.companyinfo2.view_product %}#}
                <li>
                    <a href="{% url 'companyinfo_product_list_urlpattern' %}">
                        Products</a></li>
{#            {% endif %}#}

{#            {% if perms.companyinfo2.view_part %}#}
                <li>
                    <a href="{% url 'companyinfo_part_list_urlpattern' %}">
                        Parts</a></li>
{#            {% endif %}#}

{#            {% if perms.companyinfo2.view_supplier %}#}
                <li>
                    <a href="{% url 'companyinfo_supplier_list_urlpattern' %}">
                        Suppliers</a></li>
{#            {% endif %}#}


{#            {% if perms.companyinfo2.view_coordinator %}#}
                <li>
                    <a href="{% url 'companyinfo_coordinator_list_urlpattern' %}">
                        Coordinators</a></li>
{#            {% endif %}#}


{#            {% if perms.companyinfo2.view_product_coordinator %}#}
                <li>
                    <a href="{% url 'companyinfo_product_coordinator_list_urlpattern' %}">
                        Product_coordinators</a></li>
{#            {% endif %}#}


{#            <li>#}
{#                <a href="{% url 'about_urlpattern' %}">#}
{#                    About</a></li>#}

        </ul>
    </nav>
    <main>
        {% block content %}
            This is default content!
        {% endblock %}
    </main>
</div><!-- end of container -->

<footer>
    <p>
        <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
            <img alt="Creative Commons License" style="border-width:0"
                 src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png"/>
        </a><br/><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">EZ Company</span>
        by
        <a xmlns:cc="http://creativecommons.org/ns#" href="https://www.ligent.net" property="cc:attributionName"
           rel="cc:attributionURL">Ligent, LLC</a> are licensed under a
        <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike
            4.0 International License</a>.
    </p>
</footer>

</body>
</html>

templates/companyinfo/coordinator_detail.html
{% extends 'companyinfo/base.html' %}

{% block title %}
    Coordinator - {{ coordinator }}
{% endblock %}

{% block content %}
<article>
  <div class="row">
  <div class="offset-by-two eight columns">
    <h2>{{ coordinator }}</h2>
    <ul class="inline">
{#        {% if perms.companyinfo2.change_coordinator %}#}
        <li>
          <a href="{{ coordinator.get_update_url }}"
          class="button">
            Edit Coordinator</a></li>
{#        {% endif %}#}
{#        {% if perms.companyinfo2.delete_coordinator %}#}
          <a href="{{ coordinator.get_delete_url }}"
          class="button">
            Delete Coordinator</a></li>
{#        {% endif %}#}
    </ul>
    <section>
        <table>
            <tr>
                <th>First Name:</th>
                <td>{{ coordinator.first_name }}</td>
            </tr>
            <tr>
                <th>Last Name:</th>
                <td>{{ coordinator.last_name }}</td>
            </tr>
            {% if coordinator.nickname %}
                <tr>
                    <th>Nickname:</th>
                    <td>{{ coordinator.nickname }}</td>
                </tr>
            {% endif %}
        </table>
    </section>

    <section>
        <h3>Product Coordinator</h3>
        <ul>
            {% for product_coordinator in product_coordinator_list %}
                <li>
                    <a href="{{ product_coordinator.get_absolute_url }}">{{ product_coordinator.product }}</a>
                </li>
            {% empty %}
                <li><em>This coordinator is not currently registered for any products.</em></li>
            {% endfor %}
        </ul>
    </section>

  </div></div> <!-- row -->

</article>
{% endblock %}

templates/companyinfo/product_coordinator_detail.html
{% extends 'companyinfo/base.html' %}

{% block title %}
    Product_coordinator - {{ product_coordinator }}
{% endblock %}

{% block content %}
<article>
  <div class="row">
  <div class="offset-by-two eight columns">
    <h2>{{ coordinator }}</h2>
    <ul class="inline">
{#        {% if perms.companyinfo2.change_coordinator %}#}
        <li>
          <a href="{{ product_coordinator.get_update_url }}"
          class="button">
            Edit Product_coordinator</a></li>
{#        {% endif %}#}
{#        {% if perms.companyinfo2.delete_coordinator %}#}
          <a href="{{ product_coordinator.get_delete_url }}"
          class="button">
            Delete Product_coordinator</a></li>
{#        {% endif %}#}
    </ul>
    <section>
        <table>
            <tr>
                <th>Coordinator:</th>
                <td><a href="{{ coordinator.get_absolute_url }}">{{ coordinator }}</a></td>
            </tr>
            <tr>
                <th>Product:</th>
                <td><a href="{{ product.get_absolute_url }}">{{ product }}</a></td>
            </tr>
        </table>
    </section>

  </div></div> <!-- row -->

</article>
{% endblock %}

templates/companyinfo/supplier_detail.html
{% extends 'companyinfo/base.html' %}

{% block title %}
    Supplier - {{ supplier }}
{% endblock %}

{% block content %}
    <article>
        <div class="row">
            <div class="offset-by-two eight columns">
                <h2>{{ supplier }}</h2>
                <ul class="inline">
{#                    {% if perms.companyinfo2.change_supplier %}#}
                        <li>
                            <a href="{{ supplier.get_update_url }}"
                               class="button">
                                Edit Supplier</a></li>
{#                    {% endif %}#}
{#                    {% if perms.companyinfo2.delete_supplier %}#}
                        <a href="{{ supplier.get_delete_url }}"
                           class="button">
                            Delete Supplier</a></li>
{#                    {% endif %}#}
                </ul>
                <section>
                    <table>
                        <tr>
                            <th>Supplier Name:</th>
                            <td>{{ supplier.supplier_name }}</td>
                        </tr>
                    </table>
                </section>

                <section>
                    <h3>Products</h3>
                    <ul>
                        {% for product in product_list %}
                            <li>
                                <a href="{{ product.get_absolute_url }}">{{ product }}</a>
                            </li>
                        {% empty %}
                            <li><em>There are currently no products for this supplier.</em></li>
                        {% endfor %}
                    </ul>
                </section>

            </div>
        </div> <!-- row -->

    </article>
{% endblock %}